### ISSUE TITLE
Suggestion: multiply move coordinates by 16 internally

### ISSUE THREAD

**Issue by alexyorke** [Yonom/BotBits#15]
Since move coordinates have to always be multiplied by 16, BotBits should do this internally (as it can be easy to forget.)

**Comment by Tunous** [comment]
I suggest MoveTo extensions for Actions Package that would accept coordinates or Point.

**Comment by Yonom** [comment]
I will add MoveToBlock, because anything else would be confusing. Point doesn't imply being block coordinates.
